<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vos listes denvies</name>
   <tag></tag>
   <elementGuidId>c94e5b20-2f48-4221-a539-b3174037b01f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-al-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-al-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff01dae1-c016-47da-bb73-93fe0df1c745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-title</value>
      <webElementGuid>570915f7-3f33-4b9d-a94f-a3e0518ef084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-al-title</value>
      <webElementGuid>a1a948e2-f2f3-4a8b-a048-579c33d30cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vos listes d'envies</value>
      <webElementGuid>59f7bb15-89f9-4beb-bfe7-876a873c6eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-title&quot;)</value>
      <webElementGuid>ecf20145-699d-4610-a273-ea74503c2650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8501ef09-88a2-4ede-8435-4b7af7aaa833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-title</value>
      <webElementGuid>fa0ebefd-a718-4f81-ace8-93433eaa1a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-al-title</value>
      <webElementGuid>51576740-3f19-4933-8567-7eb984880d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vos listes d'envies</value>
      <webElementGuid>9522e509-fba1-40d7-bdad-7a31efcd3b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-title&quot;)</value>
      <webElementGuid>31e1673e-820e-4591-9971-a1e06d2da06c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-al-title']</value>
      <webElementGuid>7defe07a-bbcc-4f35-82db-31e97ec4872c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-al-wishlist']/div</value>
      <webElementGuid>8dc70dd5-e3b6-473d-84b9-8eb50a50e03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commencer ici.'])[1]/following::div[2]</value>
      <webElementGuid>5469c33f-f0a6-4294-bd50-d8cfb250a6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Créer une liste'])[1]/preceding::div[1]</value>
      <webElementGuid>ac74f4ba-bab6-49de-815b-525aa7f50ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Liste d', &quot;'&quot;, 'envies universelle')])[1]/preceding::div[1]</value>
      <webElementGuid>5d9fb5ba-6768-4269-90b7-6ccebbf27308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div</value>
      <webElementGuid>235eec8d-a5be-4df3-beb6-7181c6c4006f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-al-title' and (text() = concat(&quot;Vos listes d&quot; , &quot;'&quot; , &quot;envies&quot;) or . = concat(&quot;Vos listes d&quot; , &quot;'&quot; , &quot;envies&quot;))]</value>
      <webElementGuid>ed913208-7235-4c08-8a73-4c820b1d14ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
