<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continuer sans accepter</name>
   <tag></tag>
   <elementGuidId>efa7f532-7024-4630-add4-669bf47cb5ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sp-cc-rejectall-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-rejectall-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>138cba26-698d-4924-8049-1d9f8ab6968d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-rejectall-link</value>
      <webElementGuid>2ada962b-f88c-4a33-b8bd-36e590ac89bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-emphasis</value>
      <webElementGuid>d38001e3-7186-4746-8ed1-697753d1b1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f3abba4d-915a-46cd-9ec9-76638479c8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16cfc8a0-2f2d-4214-ad24-630358f6a2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuer sans accepter</value>
      <webElementGuid>7e5c3602-cc9a-41be-acd0-70021d519830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-rejectall-link&quot;)</value>
      <webElementGuid>68dff135-bbba-4627-a9a0-9cab788161e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sp-cc-rejectall-link']</value>
      <webElementGuid>72aa7cff-d397-4e1d-a0c6-e5eb4e3d7901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sp-cc-rejectall-container']/a</value>
      <webElementGuid>47511f40-f189-4003-9ae7-e0b0e1b951d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continuer sans accepter')]</value>
      <webElementGuid>2700abae-c7a4-4cec-990b-f6b12f27ef5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choisir vos préférences en matière de cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>5ae5e310-388c-4bfd-a4df-e6a93f28fbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avis sur les cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>5fcdb9ad-4fef-45a0-9947-03772fff057d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuer sans accepter']/parent::*</value>
      <webElementGuid>409ea309-b819-492d-83d9-7117592bca06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>8510b4a2-40a3-4316-81da-3284a1ba6823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>11e49ab8-afed-4d4a-bf21-5448f448075a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sp-cc-rejectall-link' and @href = '#' and (text() = 'Continuer sans accepter' or . = 'Continuer sans accepter')]</value>
      <webElementGuid>456ae9d6-d45b-43c8-b273-109161008c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
