<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fr_nav-packard-glow-loc-icon</name>
   <tag></tag>
   <elementGuidId>b2bf355d-be9a-4c4d-b83c-4276b1d5cdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-packard-glow-loc-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-packard-glow-loc-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>383b152d-16b2-4ca4-b26d-814d44a9916a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sprite nav-progressive-attribute</value>
      <webElementGuid>7eddd1f0-6e5a-4015-a5f9-9e984e785224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-packard-glow-loc-icon</value>
      <webElementGuid>93dc4c5c-6a54-4074-96e8-6347bd2527b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-packard-glow-loc-icon&quot;)</value>
      <webElementGuid>915746b3-0ed2-441b-826f-27f1c1415437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-packard-glow-loc-icon']</value>
      <webElementGuid>406c80c3-c500-427e-a7eb-36d086070c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-global-location-popover-link']/div</value>
      <webElementGuid>bfe34325-03e9-4497-9192-c89406d0d5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>118a51d1-7efe-47ed-a530-bd1ab6289825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-packard-glow-loc-icon']</value>
      <webElementGuid>740df311-c8e8-4333-89ab-5b73e2a2a162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
