<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vos Livraisons Programmes</name>
   <tag></tag>
   <elementGuidId>50e57860-f646-4172-9ace-928a164f6817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-al-your-account']/a[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09a16df0-3e96-4eff-b6aa-3b9e84589277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auto-deliveries?ref_=nav_AccountFlyout_sns</value>
      <webElementGuid>eb29e7ef-6242-4108-8b75-58f9f3ca1305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-item</value>
      <webElementGuid>a689d7d3-3b07-4c09-b21e-55b5e0e5124b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vos Livraisons Programmées</value>
      <webElementGuid>3e3d1e1f-1e7f-4cd9-a922-cf6e1577ab0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-your-account&quot;)/a[@class=&quot;nav-link nav-item&quot;]</value>
      <webElementGuid>145aebf6-e515-4678-bd76-b9f14a421c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da8e2c99-1fad-40d1-8761-eae7b26f929e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auto-deliveries?ref_=nav_AccountFlyout_sns</value>
      <webElementGuid>8af166e8-5dcb-4618-8a5b-ded529b3fa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-item</value>
      <webElementGuid>68c50f73-caf3-48f8-ad64-e78ce33c1b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vos Livraisons Programmées</value>
      <webElementGuid>cdf84f8c-3475-4a2d-a089-ac773eb9b066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-your-account&quot;)/a[@class=&quot;nav-link nav-item&quot;]</value>
      <webElementGuid>4dc3b12d-44a5-4ffd-9ab9-b93c9c08d4d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-al-your-account']/a[6]</value>
      <webElementGuid>7821b93c-62a5-4280-b556-dbca676510b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vos animaux de compagnie'])[1]/following::a[1]</value>
      <webElementGuid>24133e45-cd00-4536-a480-d2e99d1344df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vos recommandations'])[1]/following::a[2]</value>
      <webElementGuid>458dbb08-a95b-435e-a585-66d085d7fe87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adhésions et abonnements'])[1]/preceding::a[1]</value>
      <webElementGuid>e4687b6c-316e-4a9e-a141-e9be3a4217f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auto-deliveries?ref_=nav_AccountFlyout_sns')]</value>
      <webElementGuid>c5e38cda-c6d0-4981-aa75-7749310484d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[6]</value>
      <webElementGuid>b707dcd3-52cc-4a37-a434-ba2c380896d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auto-deliveries?ref_=nav_AccountFlyout_sns' and (text() = 'Vos Livraisons Programmées' or . = 'Vos Livraisons Programmées')]</value>
      <webElementGuid>36de7f9c-b652-4241-a95c-8672c7d3a44a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
