<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Votre compte</name>
   <tag></tag>
   <elementGuidId>e9553a73-19e2-4a72-977f-aded1564b4b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-al-your-account']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-al-your-account > a.nav-link.nav-item > span.nav-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7f0985a-4387-45d3-b4b7-adcd608b4235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-text</value>
      <webElementGuid>1a83f801-7926-4096-b9f7-17e611975e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Votre compte</value>
      <webElementGuid>ef0f65b3-337a-4931-8946-ee5d72c2675f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-your-account&quot;)/a[@class=&quot;nav-link nav-item&quot;]/span[@class=&quot;nav-text&quot;]</value>
      <webElementGuid>6184b398-ef7c-478a-b5cf-13fd9f5371ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f725181-06a9-4eaa-b36a-362b53ca2643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-text</value>
      <webElementGuid>b8a7444d-4dad-4837-87cf-614e03318c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Votre compte</value>
      <webElementGuid>6f8e4501-d61a-4eda-9252-0f365e36dea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-your-account&quot;)/a[@class=&quot;nav-link nav-item&quot;]/span[@class=&quot;nav-text&quot;]</value>
      <webElementGuid>3f67ac41-ef2b-4715-8735-91c38d4d60eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-al-your-account']/a/span</value>
      <webElementGuid>85e1b9ef-d0ed-407b-baa4-3838f3b6506f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Votre compte'])[1]/following::span[1]</value>
      <webElementGuid>170380c3-b7b4-4984-932f-a8915d01cfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explorez le showroom'])[1]/following::span[1]</value>
      <webElementGuid>2fcc16a3-d683-4d7d-9ac9-a00cfd9c89ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vos commandes'])[1]/preceding::span[1]</value>
      <webElementGuid>7e40c9e0-3bc5-45ad-bdf5-26ac918d6e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Votre liste d', &quot;'&quot;, 'envies')])[1]/preceding::span[2]</value>
      <webElementGuid>57ec3223-3db8-478d-bcc8-b9405de8cff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>6693e5c1-a0f1-4d32-a98c-9a803454ec58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Votre compte' or . = 'Votre compte')]</value>
      <webElementGuid>0268e0ef-82e5-42c8-85ea-c2fd4ad13f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
