<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Votre_compteVotre</name>
   <tag></tag>
   <elementGuidId>deac7f02-a3b1-47ef-84d4-8f823582b455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-al-your-account']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-al-your-account</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7492445f-b657-4388-8e82-68036574a6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-al-your-account</value>
      <webElementGuid>6e123c66-e13f-4d7f-9329-caf597874f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-al-column nav-template nav-flyout-content nav-tpl-itemList nav-flyout-accessibility</value>
      <webElementGuid>767253ae-7f75-4876-ad6f-201b7c9f41ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Votre compteVotre compte Vos commandes Votre liste d'envies Vos recommandations Vos animaux de compagnie Vos Livraisons Programmées Adhésions et abonnements Votre compte Amazon Prime Créer un compte professionnel gratuit Gérer votre contenu et vos appareils Votre Abonnement Kindle Votre bibliothèque musicale Votre Prime Video Votre Amazon Drive Votre Bibliothèque de jeux et logiciels Vos applis et vos appareils</value>
      <webElementGuid>28bf4ae4-3e61-4307-9bc2-367be22db677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-your-account&quot;)</value>
      <webElementGuid>c2a5ea82-5920-4702-9421-0bcc2ad477f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-al-your-account']</value>
      <webElementGuid>02773254-4056-4db9-8b16-25e2b9a559f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-al-container']/div[3]</value>
      <webElementGuid>2d4cf253-e100-41b7-be63-92c5e6503369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explorez le showroom'])[1]/following::div[1]</value>
      <webElementGuid>9eb610d0-de5e-476a-bc7d-10ab1b323c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Découvrez votre style'])[1]/following::div[1]</value>
      <webElementGuid>00046a4b-ba73-45be-aefd-3e2d6d68e756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>a8f9bf0a-de74-4809-a458-43e9b8ea9779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-al-your-account' and (text() = concat(&quot;Votre compteVotre compte Vos commandes Votre liste d&quot; , &quot;'&quot; , &quot;envies Vos recommandations Vos animaux de compagnie Vos Livraisons Programmées Adhésions et abonnements Votre compte Amazon Prime Créer un compte professionnel gratuit Gérer votre contenu et vos appareils Votre Abonnement Kindle Votre bibliothèque musicale Votre Prime Video Votre Amazon Drive Votre Bibliothèque de jeux et logiciels Vos applis et vos appareils&quot;) or . = concat(&quot;Votre compteVotre compte Vos commandes Votre liste d&quot; , &quot;'&quot; , &quot;envies Vos recommandations Vos animaux de compagnie Vos Livraisons Programmées Adhésions et abonnements Votre compte Amazon Prime Créer un compte professionnel gratuit Gérer votre contenu et vos appareils Votre Abonnement Kindle Votre bibliothèque musicale Votre Prime Video Votre Amazon Drive Votre Bibliothèque de jeux et logiciels Vos applis et vos appareils&quot;))]</value>
      <webElementGuid>78352ed6-8a82-47f1-a105-b2b1cc418f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
