<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Audible</name>
   <tag></tag>
   <elementGuidId>e71603af-06a9-4965-aac7-279c7a36f9e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c65a23f-1fc7-4e06-949f-df00e75f1094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Livres-audio-Audible-Originals/b/?ie=UTF8&amp;node=17941536031&amp;ref_=nav_cs_audible</value>
      <webElementGuid>a1ee87b3-6372-49c2-9a71-e0f28030bc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>62e7826e-c569-4192-94a1-805072d43d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>693b1e02-2911-4751-9132-b759b37a8301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>7c006359-6d32-4655-8794-914932a6aaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_11</value>
      <webElementGuid>817923e3-dc6e-47ba-bfa2-5b67847c5f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_audible</value>
      <webElementGuid>06f33367-562e-4ffc-8a2a-93eea61df152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>jl6gz1-1j4n86-sv9sx7-s5q60f</value>
      <webElementGuid>7bf5e79b-3b29-4708-9185-01f24bffe6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audible</value>
      <webElementGuid>84d06fec-7c11-4b59-94ad-13e5252c65d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>486f194c-c9d8-4256-bcec-11c2660a6f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[12]</value>
      <webElementGuid>07cfc60c-9653-4436-9dfb-198fb6498899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Audible')]</value>
      <webElementGuid>bb6dde32-7ab3-4612-9702-9bd450563669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High-Tech'])[2]/following::a[1]</value>
      <webElementGuid>21d7217c-c971-4236-b8bd-f13981e2bcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ebooks Kindle'])[1]/following::a[2]</value>
      <webElementGuid>acdc7e76-841f-4157-bf5d-a216ae92983f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Idées cadeaux'])[1]/preceding::a[1]</value>
      <webElementGuid>52255e49-14fc-4513-a4c3-3022f3a52738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuisine et Maison'])[1]/preceding::a[2]</value>
      <webElementGuid>4c552e02-e284-422a-839a-e3ad27d471e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audible']/parent::*</value>
      <webElementGuid>68eb0e61-8c99-4a51-b7c9-92fdc244151b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Livres-audio-Audible-Originals/b/?ie=UTF8&amp;node=17941536031&amp;ref_=nav_cs_audible')]</value>
      <webElementGuid>bc5f0f05-f026-4fa4-b7ba-1888bafb9223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[12]</value>
      <webElementGuid>e2d2f34b-177f-48ed-b528-c1027f1e3633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Livres-audio-Audible-Originals/b/?ie=UTF8&amp;node=17941536031&amp;ref_=nav_cs_audible' and (text() = 'Audible' or . = 'Audible')]</value>
      <webElementGuid>4890df6f-fc3a-4b2d-be23-a6668a308b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
