<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ebooks Kindle</name>
   <tag></tag>
   <elementGuidId>1e84be6e-d70b-42ac-86e8-fc61bcfcc9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01caef8d-e613-470e-9d73-1516b29ab0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ebooks-kindle/b/?ie=UTF8&amp;node=695398031&amp;ref_=nav_cs_kindle_books</value>
      <webElementGuid>0d51ad2a-5ac8-4fae-968a-ea6a949046e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>c6d75f2a-534a-402f-9b08-ad490e44a7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0585e128-755b-4552-ada4-51365aa0f134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>7563f1d9-5200-4115-9cba-270b39b6e092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_9</value>
      <webElementGuid>efe60d39-2bb5-4ab7-b2c5-9a9faac6511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_kindle_books</value>
      <webElementGuid>62cd8b7f-6035-4d80-953a-7375042afb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>z0d5w4-522unq-s4sges-w39dl7</value>
      <webElementGuid>561c204e-7525-4a9f-b570-fbfb85e797dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ebooks Kindle</value>
      <webElementGuid>69e3f9fb-20bf-4722-b584-cb0604448144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>1dc7f8b6-02f0-4a2f-b363-1800ffa7aab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[10]</value>
      <webElementGuid>adfab627-4fe2-4f24-a154-a6e25cb62d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ebooks Kindle')]</value>
      <webElementGuid>0dab9547-699f-4a70-9078-571206dbdf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Livres'])[2]/following::a[1]</value>
      <webElementGuid>ccbc06f8-d2b5-4e1a-a48a-d2359cdc25ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventes Flash'])[1]/following::a[2]</value>
      <webElementGuid>d4cc4976-ed50-446f-bd33-3540c4e0bbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High-Tech'])[2]/preceding::a[1]</value>
      <webElementGuid>3ac21738-801d-428f-9240-454ce3fe7235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audible'])[1]/preceding::a[2]</value>
      <webElementGuid>57900cea-130c-451a-a2a3-fddecaae98c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ebooks Kindle']/parent::*</value>
      <webElementGuid>2119d965-c39d-49c1-bff9-d46ff7e9a471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ebooks-kindle/b/?ie=UTF8&amp;node=695398031&amp;ref_=nav_cs_kindle_books')]</value>
      <webElementGuid>752c2932-c427-47de-bd23-5830fa078f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[10]</value>
      <webElementGuid>07de6c64-8152-40ff-b682-82c4bb664dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ebooks-kindle/b/?ie=UTF8&amp;node=695398031&amp;ref_=nav_cs_kindle_books' and (text() = 'Ebooks Kindle' or . = 'Ebooks Kindle')]</value>
      <webElementGuid>53bf47cb-ff70-434f-8ea2-b4c927851819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
