<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Listes de Souhaits_nav-imageHref</name>
   <tag></tag>
   <elementGuidId>7408ec66-7a7e-4f23-b67c-5efa43dd0bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navSwmHoliday']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-imageHref</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54704f00-0402-49d0-9486-9cc356d61181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>La Boutique de Noël - Trouvez le cadeau parfait</value>
      <webElementGuid>d5e24e15-2377-49d3-9c38-63f16c1fe219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gcx/Cadeaux-pour-Femmes-et-Hommes/gfhz/?_encoding=UTF8&amp;ref_=nav_swm_it_SWM&amp;pf_rd_p=deb26f8a-5a55-403e-ba49-4edc5ef1a5b5&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=A13V1IB3VIYZZH&amp;pf_rd_r=MEY6V3E9Q3V9ZFWJNQ79</value>
      <webElementGuid>82889195-db2f-45dd-8ab4-4c5884f9ea2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-imageHref</value>
      <webElementGuid>ee1469c8-5953-4151-ad58-e0561d9d1179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5e4774a-a6bf-4576-b71b-fed404386b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navSwmHoliday&quot;)/a[@class=&quot;nav-imageHref&quot;]</value>
      <webElementGuid>13ee13bc-45f5-47a0-986c-912ca2fc8450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navSwmHoliday']/a</value>
      <webElementGuid>e736f33b-4832-4a90-8850-cf7073b0eb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listes de Souhaits'])[1]/following::a[1]</value>
      <webElementGuid>12bede53-a06c-4e82-a60c-c1926c167281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prévoyez et Économisez'])[2]/following::a[2]</value>
      <webElementGuid>e1301338-977f-4632-b494-1f3eccb2b4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous slide'])[1]/preceding::a[3]</value>
      <webElementGuid>82933e6e-2ae7-4638-93c0-50eac5cc948e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next slide'])[1]/preceding::a[8]</value>
      <webElementGuid>e7be40ee-d1f4-40ba-9714-2d803a0cc103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gcx/Cadeaux-pour-Femmes-et-Hommes/gfhz/?_encoding=UTF8&amp;ref_=nav_swm_it_SWM&amp;pf_rd_p=deb26f8a-5a55-403e-ba49-4edc5ef1a5b5&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=A13V1IB3VIYZZH&amp;pf_rd_r=MEY6V3E9Q3V9ZFWJNQ79')]</value>
      <webElementGuid>8fe34e79-fcdd-44b1-8fa5-818ff3d19977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/a</value>
      <webElementGuid>b64a3744-ae80-47c3-a74b-de73368ecf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gcx/Cadeaux-pour-Femmes-et-Hommes/gfhz/?_encoding=UTF8&amp;ref_=nav_swm_it_SWM&amp;pf_rd_p=deb26f8a-5a55-403e-ba49-4edc5ef1a5b5&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=A13V1IB3VIYZZH&amp;pf_rd_r=MEY6V3E9Q3V9ZFWJNQ79']</value>
      <webElementGuid>c38b7b6c-0398-4f6f-abd6-6145ed14e952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
