<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Toutes</name>
   <tag></tag>
   <elementGuidId>40009efc-04e8-41c7-ba31-0ef5a98eec9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-hamburger-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a896ffa8-3114-4db5-a214-b50300855f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0)</value>
      <webElementGuid>395b5476-f73b-409f-8283-fca2fa5f0ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-hamburger-menu</value>
      <webElementGuid>f8a007f1-aabb-49a5-84e8-c7dc47b9c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0cff3f3-6133-41c2-9134-54af3eb215a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ouvrir le menu</value>
      <webElementGuid>235d559e-87eb-4704-8563-227375e2df63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>847b45f1-319a-4490-bdb4-8b8cbd6d5187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>HamburgerMenuDesktop</value>
      <webElementGuid>1d2df7f7-fa36-462b-924b-15f57977e048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>885ba7ef-4734-495c-8f12-82abd5f21462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>82z0td-mr76po-mi0oub-qe1g09</value>
      <webElementGuid>98bb0841-793f-4d26-88df-564e42fe1ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
    Toutes
  </value>
      <webElementGuid>4358716d-6436-4bb4-ab1b-427b638953bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)</value>
      <webElementGuid>53bd24a7-5baf-4fe3-a121-2a712d8183ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']</value>
      <webElementGuid>7a814b27-ddc7-48d8-9d8c-c0e9807a17d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/a</value>
      <webElementGuid>42a56634-35ad-492c-a6bd-13a0f38b5274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commencer ici.'])[2]/following::a[1]</value>
      <webElementGuid>17ca120a-5f78-4a3f-9966-8213978f1a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support Client Accessibilité'])[1]/preceding::a[1]</value>
      <webElementGuid>6a1fff66-58b9-482f-9bd4-80473e3bbf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript: void(0)')]</value>
      <webElementGuid>8919f80e-094b-49d4-8dcc-e45b8559f0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/a</value>
      <webElementGuid>098927bb-7575-4a98-8bea-822ab6fc2c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0)' and @id = 'nav-hamburger-menu' and (text() = '
    
    Toutes
  ' or . = '
    
    Toutes
  ')]</value>
      <webElementGuid>4f722a47-c6e7-4e84-9a2d-d07cb2be29c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
