<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Retours_commandes</name>
   <tag></tag>
   <elementGuidId>4aa8ca4a-776a-40aa-a9ce-f05ba9beef7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-orders</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-orders']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7d9a5ac-b58e-48b1-9904-5f72ff56a5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/css/order-history?ref_=nav_orders_first</value>
      <webElementGuid>d3b73030-c740-4aa7-ba04-cc2754861fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a nav-a-2   nav-progressive-attribute</value>
      <webElementGuid>f9972edb-4317-466b-87f3-fef14b105958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-orders</value>
      <webElementGuid>54a9a031-b752-4dc0-91f8-ab1cf081e78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22dfe553-225c-4374-bec4-1a61d9077f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Retours
  et commandes
</value>
      <webElementGuid>5bc04b53-db5f-40dd-ad7d-68f44a1c2abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-orders&quot;)</value>
      <webElementGuid>e025ae75-08b4-4b6c-8c9d-026c0a056589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de992e9a-d4c4-487b-a858-727b0255d20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/css/order-history?ref_=nav_orders_first</value>
      <webElementGuid>28ea7276-7d2e-473f-bb71-1e67a52b8d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a nav-a-2   nav-progressive-attribute</value>
      <webElementGuid>5ca1f4f5-9bbc-412f-99ff-39ac132230ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-orders</value>
      <webElementGuid>fbac2e9f-ed2e-451e-9397-69f0239f27a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fccbf466-1ee7-464c-87dc-c0b3d42bd86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Retours
  et commandes
</value>
      <webElementGuid>336d07a5-5b9c-4234-861d-6ba0eaf02570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-orders&quot;)</value>
      <webElementGuid>41cad2fb-7fde-4161-abfa-a1731d0d6fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-orders']</value>
      <webElementGuid>433bb5dd-cd8f-4577-baf6-8111f0788f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tools']/a[2]</value>
      <webElementGuid>01620e0b-8e3e-4822-9f3b-578e907ff5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compte et listes'])[1]/following::a[1]</value>
      <webElementGuid>76ded73e-ccd3-4a80-a419-35613ff16095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonjour, Identifiez-vous'])[1]/following::a[1]</value>
      <webElementGuid>da626309-1bfe-4b1f-b519-1caff9a2b9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/css/order-history?ref_=nav_orders_first')]</value>
      <webElementGuid>58c78c65-b4e5-42ba-bcce-8f66c1da61ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[2]</value>
      <webElementGuid>9cfdd01f-f944-4669-a2a9-ea236bd6aea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/css/order-history?ref_=nav_orders_first' and @id = 'nav-orders' and (text() = '
  Retours
  et commandes
' or . = '
  Retours
  et commandes
')]</value>
      <webElementGuid>cc67c4bf-d9ca-4a83-9824-171c517f5b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
