<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Identifiez-vous_All_Elements</name>
   <tag></tag>
   <elementGuidId>747d8e6e-900d-4f7f-9e29-c7398c3be746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-accountList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-accountList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c6ec89e-3724-4d14-ba48-de04325426e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-flyout-accountList</value>
      <webElementGuid>0262b6f9-af68-42da-bdd5-b5c9be4b55d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-coreFlyout nav-flyout</value>
      <webElementGuid>4451f876-d746-4b66-ab25-c7bfb57586af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identifiez-vousNouveau client ? Commencer ici.Vos listes d'enviesCréer une liste Liste d'envies universelle Liste de mariage Liste de naissance Découvrez votre style Explorez le showroomVotre compteVotre compte Vos commandes Votre liste d'envies Vos recommandations Vos animaux de compagnie Vos Livraisons Programmées Adhésions et abonnements Votre compte Amazon Prime Créer un compte professionnel gratuit Gérer votre contenu et vos appareils Votre Abonnement Kindle Votre bibliothèque musicale Votre Prime Video Votre Amazon Drive Votre Bibliothèque de jeux et logiciels Vos applis et vos appareils</value>
      <webElementGuid>5959cf85-6a5c-4cca-aeac-15844e1b87fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-accountList&quot;)</value>
      <webElementGuid>9f957e19-2f62-443c-95ff-76ac0b5c071e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-accountList']</value>
      <webElementGuid>7b503de2-a86f-4fa9-bdb7-d706b94669ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-anchor']/div[3]</value>
      <webElementGuid>3d0bd17e-efc7-4732-943b-37599e2c9678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='et commandes'])[1]/following::div[24]</value>
      <webElementGuid>9e5b3e30-5df4-4c50-bc4c-f4c8b801f103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retours'])[1]/following::div[24]</value>
      <webElementGuid>4c25653a-1682-44da-b1ed-9847e8ca222f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>d028fc53-5827-40ac-805a-86159170a768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-flyout-accountList' and (text() = concat(&quot;Identifiez-vousNouveau client ? Commencer ici.Vos listes d&quot; , &quot;'&quot; , &quot;enviesCréer une liste Liste d&quot; , &quot;'&quot; , &quot;envies universelle Liste de mariage Liste de naissance Découvrez votre style Explorez le showroomVotre compteVotre compte Vos commandes Votre liste d&quot; , &quot;'&quot; , &quot;envies Vos recommandations Vos animaux de compagnie Vos Livraisons Programmées Adhésions et abonnements Votre compte Amazon Prime Créer un compte professionnel gratuit Gérer votre contenu et vos appareils Votre Abonnement Kindle Votre bibliothèque musicale Votre Prime Video Votre Amazon Drive Votre Bibliothèque de jeux et logiciels Vos applis et vos appareils&quot;) or . = concat(&quot;Identifiez-vousNouveau client ? Commencer ici.Vos listes d&quot; , &quot;'&quot; , &quot;enviesCréer une liste Liste d&quot; , &quot;'&quot; , &quot;envies universelle Liste de mariage Liste de naissance Découvrez votre style Explorez le showroomVotre compteVotre compte Vos commandes Votre liste d&quot; , &quot;'&quot; , &quot;envies Vos recommandations Vos animaux de compagnie Vos Livraisons Programmées Adhésions et abonnements Votre compte Amazon Prime Créer un compte professionnel gratuit Gérer votre contenu et vos appareils Votre Abonnement Kindle Votre bibliothèque musicale Votre Prime Video Votre Amazon Drive Votre Bibliothèque de jeux et logiciels Vos applis et vos appareils&quot;))]</value>
      <webElementGuid>878071f6-121d-4f8c-9ba5-c99ebe24a1e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
