<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fr_nav-packard-glow-loc-icon</name>
   <tag></tag>
   <elementGuidId>62c6423b-3809-4172-9dbf-1e3c215647a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-packard-glow-loc-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-packard-glow-loc-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b59b56e-7c9a-443f-907f-c515ef382d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sprite nav-progressive-attribute</value>
      <webElementGuid>42b52c0a-1e28-40f0-bf43-fb4c1d25feb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-packard-glow-loc-icon</value>
      <webElementGuid>0f71b6fb-ba52-493a-b8cc-f7dc59422d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-packard-glow-loc-icon&quot;)</value>
      <webElementGuid>af8c9deb-0399-4ee3-ac8e-f7574061f9a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-packard-glow-loc-icon']</value>
      <webElementGuid>c734bd65-29c4-4ae7-a667-43525bb0184b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-global-location-popover-link']/div</value>
      <webElementGuid>3c3c3fd6-dcbb-4a92-82be-4c0349691a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>b3ca3c8e-c5e7-48da-8e41-d6f03b0fcd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-packard-glow-loc-icon']</value>
      <webElementGuid>f6bb540e-ab0d-4498-81e0-487b85dc6331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
