<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continuer sans accepter</name>
   <tag></tag>
   <elementGuidId>ce12f66b-faf5-423d-9d05-e75613903fa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-rejectall-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sp-cc-rejectall-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5d472e8-7e05-4ef4-a8cc-d8f0522078e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-rejectall-link</value>
      <webElementGuid>6796c7c9-b3cf-4b2d-a071-4efc2fd6dab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-emphasis</value>
      <webElementGuid>576529b8-854b-4288-a660-365245a7b77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b1096444-880b-4d44-8cac-0701827aca92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ed91e47-c732-49d0-bffd-d85377830da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuer sans accepter</value>
      <webElementGuid>7f41ec45-a4a1-4e76-aaf2-8f6e589cd405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-rejectall-link&quot;)</value>
      <webElementGuid>74e2149b-014b-4248-adb3-eaf4d2e659b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sp-cc-rejectall-link']</value>
      <webElementGuid>e117cb6d-9ef9-40e4-a80a-4dae99e0664b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sp-cc-rejectall-container']/a</value>
      <webElementGuid>7b42aa01-18d9-472d-8575-c97f34a46da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continuer sans accepter')]</value>
      <webElementGuid>1855350f-a2a7-4e7c-9a17-2b35876ff33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choisir vos préférences en matière de cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>30de8d61-798e-40cd-adc3-9183fff906a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avis sur les cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>47949166-64da-474e-adfd-6d25a6b2a4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuer sans accepter']/parent::*</value>
      <webElementGuid>6f2e5f6b-cc8a-47a2-95d6-aa14f12b7b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>2ad04d6a-f648-45dc-8dfc-6401b4253610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>045f6b56-4fcd-4fda-89ed-a983cd552126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sp-cc-rejectall-link' and @href = '#' and (text() = 'Continuer sans accepter' or . = 'Continuer sans accepter')]</value>
      <webElementGuid>65dab6c4-2623-447d-82d5-766ec73a7747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
