<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Identifiez-vousNouveau_client_Commencer ici</name>
   <tag></tag>
   <elementGuidId>49a3b8f5-eaef-44b1-9011-dd1f6299f286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-al-signin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-al-signin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37c44eb5-a085-4757-b5b5-4f899ba3fe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-al-signin</value>
      <webElementGuid>5e676543-2ed7-490b-be6b-ca93b88de903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identifiez-vousNouveau client ? Commencer ici.</value>
      <webElementGuid>11a7d0f0-0b39-48c4-96d5-11e9da7c4388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-al-signin&quot;)</value>
      <webElementGuid>f761921e-28ff-446c-9be0-637e7e095d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-al-signin']</value>
      <webElementGuid>26c69559-7383-41cc-87a8-25d3709e2db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-al-container']/div</value>
      <webElementGuid>d016841b-424d-4450-ada3-e25061f8080d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='et commandes'])[1]/following::div[29]</value>
      <webElementGuid>6aef36c9-ff69-44be-bc12-84c587852d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retours'])[1]/following::div[29]</value>
      <webElementGuid>e5cebdf5-5c9d-420e-91f6-78183cbb68bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div</value>
      <webElementGuid>ca391d33-4974-4cad-9623-c74d966c7ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-al-signin' and (text() = 'Identifiez-vousNouveau client ? Commencer ici.' or . = 'Identifiez-vousNouveau client ? Commencer ici.')]</value>
      <webElementGuid>780113b2-9955-4eae-a8db-e08384c69016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
