<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Politique de confidentialit_accept</name>
   <tag></tag>
   <elementGuidId>47fb96a3-e8d3-43ae-a834-63e89dd8658a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sp-cc-accept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-accept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>616f8765-658a-41d9-9527-ac28c651ce4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-accept</value>
      <webElementGuid>29d1922f-e9b4-44cb-b92a-4c3b19b87ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ddfa14db-73d7-447f-969e-d2c9b99b1235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept</value>
      <webElementGuid>717f8182-d7c0-4e7c-aa47-1c6b0b9d57ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input celwidget</value>
      <webElementGuid>d635e737-2ea4-4c2c-8634-a2286e39578d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5c2f1796-7014-4998-a858-408b5489f558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>a870a604-7538-4942-aeb4-c932a11a235f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>l77ld2-9x38bx-l80n94-jqbttb</value>
      <webElementGuid>0b68fabb-266d-4e7b-abf0-bd57df49032f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-accept&quot;)</value>
      <webElementGuid>10bbfba8-6db3-4b9f-ae1b-6dcff9269103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sp-cc-accept']</value>
      <webElementGuid>330205fa-b714-4751-82fe-29c3deb14b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sp-cc']/div[3]/span/span/input</value>
      <webElementGuid>3a9fe66e-3ecb-411b-b88f-4df5fdcd45f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>2e0d8e50-4a7c-49a0-9b72-e090cb518361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sp-cc-accept' and @name = 'accept' and @type = 'submit']</value>
      <webElementGuid>e972e971-4024-4ba3-b8eb-4187abc91b2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
