<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Politique de confidentialit_accept</name>
   <tag></tag>
   <elementGuidId>e36c5b4c-22c1-497e-a4d1-9778995b1c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sp-cc-accept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-accept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5e686e6-c8a7-40bc-a31c-dc2240c36ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-accept</value>
      <webElementGuid>7a16bd09-b56a-4536-96ec-00ee4642c8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a1f22d4f-8e9b-42ae-ae67-d483238705bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept</value>
      <webElementGuid>23092735-e04a-4c95-a323-d8816f144939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input celwidget</value>
      <webElementGuid>78c195f9-8d3b-490d-addc-05d09d79eafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b9837bdf-c17e-4872-bc2b-4e6d7a85bea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>b0fda21e-7b1e-4743-84e7-3ed0ac1c03db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>155b1c9d-57eb-4f12-9720-5585b5faeb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>xfwwe-eiai4l-lyj0tu-mwft7v</value>
      <webElementGuid>9d700db1-5e7b-4b20-8b63-dcf59b53b69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cel-widget</name>
      <type>Main</type>
      <value>sp-cc-accept</value>
      <webElementGuid>6e48aef9-0afd-4401-9758-5b8a3d7e42a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-accept&quot;)</value>
      <webElementGuid>3ca8ac18-4dd6-4ec3-bf46-269f5d2bb1dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sp-cc-accept']</value>
      <webElementGuid>3b932bf0-4a2a-4242-a9d8-2f4f6cb2da13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>873d9e05-5858-4e27-b54d-27e18ee38a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>724c0ee6-40be-4235-8eb6-cafb02b8955b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sp-cc-accept' and @name = 'accept' and @type = 'submit']</value>
      <webElementGuid>e4f923a8-cede-41e1-9841-b7143ba973b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
